# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The quest of a developer
email: marinus@familiegeuze.nl
description: > # this means to ignore newlines until "baseurl:"
  The site contains the blogs which report on the
  the quest of a developer to new architectural concepts, design/coding techniques,
  frameworks and libraries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/marinusgeuze" # the base hostname & protocol for your site
twitter_username: MarinusGeuze
github_username:  marinusgeuze

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag